# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-19 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.UserRole'),
        ),
    ]
